name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 82.29.161.195 >> ~/.ssh/known_hosts
          
          # Test SSH connection
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no root@82.29.161.195 "echo 'SSH connection successful!'"
          
          echo "SSH test completed successfully!" 